cse110-sp24-group27/cse110-sp24-group27

- individual-project.html
Added the basic structure of an individual project page:
2 main sections:
1. Project header which contains:
- Project name
- Project description
- Table of contents
2. Journal entries
Also contains:
- Button for adding new journal entries (need to add popup for this in the future)
- Footer for copyright (similar to Timothy's project profile page)
> Added individual project page HTML file

- individual-project.html
- source/assets/styles/styles.css
Added some preliminary CSS to make the page look roughly like the design.
Design details are of course not set and can be changed in the future.
> Added individual project page basic CSS

- individual-project.html
- source/assets/styles/styles.css
Added a back button. Centered main content. Moved "add project" button and copyright.
> Edited individual project page HTML/CSS

- project.html
- source/assets/styles/project_styles.css
Created project_styles.css for project home page.
<br>Modified project.html to match requirements.
> created project_styles.css and modified project home page's HTML structure

- home_projects_page.html
Added JS code for going to Project Home Page after clicking the Home Button in the menu bar. <br>
The link of Project Home Page might need to be changed once the page is published because of the change of domain.
> added JS for Home button in Project Home Page

- home_projects_page.html
- source/assets/scripts/main.js
- source/assets/styles/project_styles.css
Deleted ```type="module"``` from ```<script src="../assets/scripts/main.js" type="module"></script>```. <br>
Added ```newProject``` and ```addProject``` functions in main.js to add event listener for + button and Done button. The implementation of ```addProject``` is not finished as it doesn't submit the form right but hide the form.
> Solved merge conflict

- source/reference/cardTemplate.html
Created cardTemplate.html according to the structure of  cardTemplate.html in lab7.
<br> This will serve as the template of the html and css structure of each Project Card.
> created cardTemplate.html as html and css template for each project card

- home_projects_page.html
- source/assets/scripts/ProjectCard.js
- source/assets/scripts/home_projects_page.js
- source/assets/scripts/main.js
- source/assets/styles/project_styles.css
- source/reference/cardTemplate.html
I have changed the html and css initialization of the project card in main.js. It seems that the original method of calling the project_styles.css didn't work, so I changed to manually input the css styles and html elements of each project card.
<br> I have also moved the onclick functions from main.js to home_projects_page.js to not mess up main.js for now.
<br> Each project card from the .json file is displayed correctly. I have added a word-limitation (30 words) for the ```project-description``` to not let the descriptions be outside of the project box boundary.
> modified Project Card html and css 

- source/assets/styles/styles.css
- source/reference/selected_project_page.html
Current page status:
Changes:
- Added task bar
- Edited margins and positioning to adjust for the task bar and to match the project homepage
- Edited "back" and "drag" buttons to stay proportional and not to get too small or too large when the window is resized
> Edited project page HTML/CSS

- source/assets/styles/project_setting.css
- source/reference/datastructure.json
- source/reference/project_setting.html
current look for profile setting:
> Profile setting

- home_projects_page.html
- source/assets/scripts/ProjectCard.js
- source/assets/styles/project_styles.css
- source/reference/project_setting.html
Changes:
- correct the paths to the logo and project_setting.css in project_setting.html
- correct the link value of `location.href` to the home page and the setting page
- add `localstorage` to profile so that the updated profile values always store in `localstorage`
> modified Setting buttons

- source/assets/scripts/profile_setting.js
- source/reference/project_setting.html
Changes:
- created source/assets/scripts/profile_setting.js
- implemented `localstorage` for user's profile info.
- used source/reference/datastructure.json as an example .JSON input file, and create the localstorage from it
Things need to be done:
- update the setting page and home page according to values of `profile` in `localstorage`
- the text color in the input box needs to be changed (can barely read the words)
- need to store `profile` into a .JSON file
> added localstorage for profile

- home_projects_page.html
- source/assets/scripts/main.js
- source/assets/scripts/profile_setting.js
- source/assets/styles/project_setting.css
- source/assets/styles/project_styles.css
- source/reference/datastructure.json
- source/reference/project_setting.html
- added function to get profile from localstorage and update the profile in home page
- modified script in profile_setting.html to make the values of profile in localstorage always stay the same even if the input is empty (might not be an ideal solution though but works for now)
- the username input box is not implemented yet
- need to comment out fetchProfileExamplejsonToStorage() in both main.js and profile_setting.js because it always changes values of profile. Need to modify this to only fetch profile example from .JSON when first open the webpage
> added function to update profile

- home_projects_page.html
- source/reference/project_setting.html
- source/reference/selected_project_page.html
I noticed that not all the pages linked properly to the expected places. I've added JS links to all the HTML templates allowing for seamless transition between the pages.
> Made the links accessible for all developers.

- source/assets/scripts/main.js
- source/assets/styles/project_styles.css
Fixed problem that changes made yesterday regarding to localstorage wasn't saved and merged to main repo.
<br> Now the program will only fetch the .JSON file once when the page first loaded. 
<br> Also, the styling of the project home page is improved.
> fixed error in localstorage for profile and projects

- source/assets/styles/project_setting.css
- source/reference/project_setting.html
The only last changes we need is updating the CRUD applications accordingly after the renaming.
> finalized styling of the settings page

- source/assets/styles/styles.css
- source/reference/selected_project_page.html
I've reduced the amount of text in the description and removed the template text. I plan to reorganize the styles of the entire journal entry box but am unsure of where to find that. Also, what styling tags did you apply to the table of contents? @dey003
> got rid of the template section of the journal entry

- home_projects_page.html
- source/assets/scripts/ProjectCard.js
- source/assets/scripts/home_projects_page.js
- source/assets/scripts/selected_project_page.js
- source/assets/styles/styles.css
- source/reference/selected_project_page.html
Closing this issue would also close issue #118
> 117 communication from homepage to selected project page

- source/assets/scripts/selected_project_page.js
- source/assets/styles/styles.css
- source/reference/selected_project_page.html
Changes:
- Fixed copyright positioning
- Made the project title and description match the values stored in `localStorage`
> Updates to HTML/CSS/JS for project page

- source/assets/scripts/selected_project_page.js
- source/reference/selected_project_page.html
Changes:
- Implemented new "add" button pop-up so that entries are added to localStorage and the project page
> Implemented new "add" button pop-up in project page

- source/assets/scripts/selected_project_page.js
- source/assets/styles/styles.css
Changes:
- Fixed the function for creating a dynamic table of contents
- Made the copyright position fixed instead of absolute
> Fixed dynamic table of contents function in project page

- source/reference/selected_project_page.html
Changes:
- Removed default table of contents item and default journal entry since localStorage entries are implemented
> Removed default table of contents and journal entry values

- source/assets/scripts/ProjectCard.js
- source/assets/scripts/selected_project_page.js
Changes:
- Readded the function for loading the dynamic table of contents in the project page; the function seems to have been deleted at some point
> Readded dynamic table of contents to project page

- source/assets/scripts/selected_project_page.js
Changes:
- Table of contents now updates when adding a new journal entry in the project page
> Made table of contents update when adding journal entry

- source/assets/scripts/selected_project_page.js
Changes:
- Table of contents now updates after deleting a journal entry in the project page
> Update table of contents upon journal entry deletion

- coverage/clover.xml
- source/assets/scripts/+_button_selcted_project_page.js
- source/assets/scripts/main.js
- source/tests/+_button.unit.js
- source/tests/main.unit.js
[KAN-10]
- Tests some functions of all scripts
- Aiming to reach 30%-40% test coverage
[KAN-10]: https://27wayfarers.atlassian.net/browse/KAN-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding more unit tests

- admin/meetings/060724-retrospective.md
- admin/meetings/060724-sprint-3-review.md
- admin/meetings/060724-wrapup.md
Note: the file is called "sprint-3-review" because sprint 1 was the warm-up exercise.
> Added 6/7 notes

- home_projects_page.html
Fixed relative path for the logo link on the home page
> Fixed logo link on homepage
